pgdump:
  options:
    flags:
      host: host.docker.internal
      port: 5432
      password: postgresroot
      username: postgresuser
      dbName: postgres
      format: tar
      file: /tmp/postgres.dump
    additionalArgs: []