before:
  hooks:
    - go mod download
    - make test
    - make lint
builds:
-
  env:
  - CGO_ENABLED=0
  binary: brudi
  ldflags:
    - -s
    - -w
    - -X 'github.com/mittwald/brudi/cmd.tag={{ .Tag }}'
  goos:
    - darwin
    - linux
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    image_templates:
      - quay.io/mittwald/brudi:latest
      - quay.io/mittwald/brudi:v{{ .Major }}
      - quay.io/mittwald/brudi:v{{ .Major }}.{{ .Minor }}
      - quay.io/mittwald/brudi:{{ .Tag }}
      - quay.io/mittwald/brudi:stable
    binaries:
      - brudi
    goos: linux
    goarch: amd64
    goarm: ''