#docker-compose for testing purposes
version: "2.1"

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysql
      JDBC_PARAMS: 'useSSL=false'
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always